version: "3.5"

services:
  server:
    build: "./"
    restart: unless-stopped
    command: "./server"
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:10.5
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: artyom
      POSTGRES_DB: filmbase
      PGDATA: /data/postgres
    ports:
      - "5434:5432"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/data/postgres

volumes:
  postgres: